In [14]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [15]:
df = pd.read_csv("fuel_econ.csv")
df.head()

,id,make,model,year,VClass,drive,trans,fuelType,cylinders,displ,pv2,pv4,city,UCity,highway,UHighway,comb,co2,feScore,ghgScore
0,32204,Nissan,GT-R,2013,Subcompact Cars,All-Wheel Drive,Automatic (AM6),Premium Gasoline,6,3.8,79,0,16.4596,20.2988,22.5568,30.1798,18.7389,471,4,4
1,32205,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Automatic (AM-S6),Premium Gasoline,4,2.0,94,0,21.8706,26.9770,31.0367,42.4936,25.2227,349,6,6
2,32206,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Automatic (S6),Premium Gasoline,6,3.6,94,0,17.4935,21.2000,26.5716,35.1000,20.6716,429,5,5
3,32207,Volkswagen,CC 4motion,2013,Compact Cars,All-Wheel Drive,Automatic (S6),Premium Gasoline,6,3.6,94,0,16.9415,20.5000,25.2190,33.5000,19.8774,446,5,5
4,32208,Chevrolet,Malibu eAssist,2013,Midsize Cars,Front-Wheel Drive,Automatic (S6),Regular Gasoline,4,2.4,0,95,24.7726,31.9796,35.5340,51.8816,28.6813,310,8,8

In [16]:
fuelecon = df[['id', 'make', 'model', 'year', 'VClass', 'drive', 'fuelType', 
               'feScore']].copy()

In [17]:
fuelecon.head()

,id,make,model,year,VClass,drive,fuelType,feScore
0,32204,Nissan,GT-R,2013,Subcompact Cars,All-Wheel Drive,Premium Gasoline,4
1,32205,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Premium Gasoline,6
2,32206,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Premium Gasoline,5
3,32207,Volkswagen,CC 4motion,2013,Compact Cars,All-Wheel Drive,Premium Gasoline,5
4,32208,Chevrolet,Malibu eAssist,2013,Midsize Cars,Front-Wheel Drive,Regular Gasoline,8

In [18]:
fuelecon = fuelecon.rename(columns={
    'id': 'ID',
    'make': 'Make',
    'model': 'Model',
    'year': 'Year',
    'VClass': 'Vehicle_Class',
    'drive': 'Drive',
    'fuelType': 'Fuel_Type',
    'feScore': 'Fuel_Economy_Score'
})

In [19]:
fuelecon['Good Fuel Economy?'] = np.where(fuelecon['Fuel_Economy_Score'] > 6, 'yes', 'no')

In [20]:
fuelecon.set_index('ID', inplace = True)

In [21]:
fuelecon.sample(5)

,Make,Model,Year,Vehicle_Class,Drive,Fuel_Type,Fuel_Economy_Score,Good Fuel Economy?
ID,,,,,,,,
32725,Mercedes-Benz,S550,2013,Large Cars,Rear-Wheel Drive,Premium Gasoline,4,no
34640,Volkswagen,Beetle,2014,Compact Cars,Front-Wheel Drive,Regular Gasoline,7,yes
32910,BMW,335is Coupe,2013,Subcompact Cars,Rear-Wheel Drive,Premium Gasoline,4,no
35439,Dodge,Challenger,2015,Midsize Cars,Rear-Wheel Drive,Premium Gasoline,4,no
33159,Honda,Insight,2013,Compact Cars,Front-Wheel Drive,Regular Gasoline,10,yes

In [22]:
fuelecon[fuelecon["Model"]== "Mustang Convertible"]

,Make,Model,Year,Vehicle_Class,Drive,Fuel_Type,Fuel_Economy_Score,Good Fuel Economy?
ID,,,,,,,,
32248,Ford,Mustang Convertible,2013,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
33430,Ford,Mustang Convertible,2014,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
35860,Ford,Mustang Convertible,2015,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,4,no
35861,Ford,Mustang Convertible,2015,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
36879,Ford,Mustang Convertible,2016,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
36883,Ford,Mustang Convertible,2016,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,4,no
37575,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
37579,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no
37584,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
37585,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no
39644,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
39647,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
39651,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no

In [23]:
fuelecon = fuelecon.drop_duplicates(subset=['Model'])

In [24]:
fuelecon[fuelecon["Model"]== "Mustang Convertible"]

,Make,Model,Year,Vehicle_Class,Drive,Fuel_Type,Fuel_Economy_Score,Good Fuel Economy?
ID,,,,,,,,
32248,Ford,Mustang Convertible,2013,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no

In [29]:
rds_connection_string = "postgres:7924@localhost:5432/ETL_proj"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [30]:
engine.table_names()

['sales_df_yr', 'fueleconomy']

In [31]:
fuelecon.to_sql(name='fueleconomy', con=engine, if_exists='replace', index=True)

In [32]:
with engine.connect() as con:
    con.execute('ALTER TABLE fueleconomy ADD PRIMARY KEY ("Model", "Year");')