In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv("fuel_econ.csv")
df

,id,make,model,year,VClass,drive,trans,fuelType,cylinders,displ,pv2,pv4,city,UCity,highway,UHighway,comb,co2,feScore,ghgScore
0,32204,Nissan,GT-R,2013,Subcompact Cars,All-Wheel Drive,Automatic (AM6),Premium Gasoline,6,3.8,79,0,16.4596,20.2988,22.5568,30.1798,18.7389,471,4,4
1,32205,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Automatic (AM-S6),Premium Gasoline,4,2.0,94,0,21.8706,26.9770,31.0367,42.4936,25.2227,349,6,6
2,32206,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Automatic (S6),Premium Gasoline,6,3.6,94,0,17.4935,21.2000,26.5716,35.1000,20.6716,429,5,5
3,32207,Volkswagen,CC 4motion,2013,Compact Cars,All-Wheel Drive,Automatic (S6),Premium Gasoline,6,3.6,94,0,16.9415,20.5000,25.2190,33.5000,19.8774,446,5,5
4,32208,Chevrolet,Malibu eAssist,2013,Midsize Cars,Front-Wheel Drive,Automatic (S6),Regular Gasoline,4,2.4,0,95,24.7726,31.9796,35.5340,51.8816,28.6813,310,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3924,39882,Toyota,Prius Prime,2018,Midsize Cars,Front-Wheel Drive,Automatic (variable gear ratios),Regular Gasoline,4,1.8,0,0,55.2206,78.8197,53.0000,73.6525,54.4329,78,10,10
3925,39898,Hyundai,Sonata Hybrid,2018,Midsize Cars,Front-Wheel Drive,Automatic (AM6),Regular Gasoline,4,2.0,0,106,39.0000,55.9000,44.3066,64.0000,41.0000,217,9,9
3926,39899,Hyundai,Sonata Hybrid SE,2018,Midsize Cars,Front-Wheel Drive,Automatic (AM6),Regular Gasoline,4,2.0,0,106,40.0000,56.0000,46.0000,64.0000,42.0000,212,9,9
3927,39900,Lexus,LS 500,2018,Midsize Cars,Rear-Wheel Drive,Automatic (S10),Premium Gasoline,6,3.4,99,0,19.2200,24.2000,30.2863,43.4000,23.0021,387,5,5
3928,39901,Lexus,LS 500 AWD,2018,Midsize Cars,All-Wheel Drive,Automatic (S10),Premium Gasoline,6,3.4,99,0,18.0431,22.6000,27.0000,39.3000,21.3945,417,4,4

In [3]:
fuelecon = df[['id', 'make', 'model', 'year', 'VClass', 'drive', 'fuelType', 
               'feScore']].copy()

In [4]:
fuelecon.head()

,id,make,model,year,VClass,drive,fuelType,feScore
0,32204,Nissan,GT-R,2013,Subcompact Cars,All-Wheel Drive,Premium Gasoline,4
1,32205,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Premium Gasoline,6
2,32206,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Premium Gasoline,5
3,32207,Volkswagen,CC 4motion,2013,Compact Cars,All-Wheel Drive,Premium Gasoline,5
4,32208,Chevrolet,Malibu eAssist,2013,Midsize Cars,Front-Wheel Drive,Regular Gasoline,8

In [5]:
fuelecon = fuelecon.rename(columns={
    'VClass': 'vehicle_class',
    'drive': 'drive',
    'fuelType': 'fuel_type',
    'feScore': 'fuel_economy_score'
})

In [6]:
fuelecon['good_fuel_economy?'] = np.where(fuelecon['fuel_economy_score'] > 6, 'yes', 'no')

In [7]:
fuelecon.set_index('id', inplace = True)

In [8]:
fuelecon.sample(5)

,make,model,year,vehicle_class,drive,fuel_type,fuel_economy_score,good_fuel_economy?
id,,,,,,,,
32969,BMW,550i,2013,Midsize Cars,Rear-Wheel Drive,Premium Gasoline,4,no
38190,Lexus,RC 350 AWD,2017,Subcompact Cars,All-Wheel Drive,Premium Gasoline,4,no
35353,Volkswagen,Golf,2015,Compact Cars,Front-Wheel Drive,Regular Gasoline,7,yes
36676,Volkswagen,Beetle,2016,Compact Cars,Front-Wheel Drive,Regular Gasoline,7,yes
35224,Chevrolet,Sonic 5 RS,2015,Midsize Cars,Front-Wheel Drive,Regular Gasoline,7,yes

In [9]:
fuelecon[fuelecon["model"]== "Mustang Convertible"]

,make,model,year,vehicle_class,drive,fuel_type,fuel_economy_score,good_fuel_economy?
id,,,,,,,,
32248,Ford,Mustang Convertible,2013,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
33430,Ford,Mustang Convertible,2014,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
35860,Ford,Mustang Convertible,2015,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,4,no
35861,Ford,Mustang Convertible,2015,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
36879,Ford,Mustang Convertible,2016,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
36883,Ford,Mustang Convertible,2016,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,4,no
37575,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
37579,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no
37584,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
37585,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no
39644,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
39647,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
39651,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no

In [13]:
fuelecon = fuelecon.drop_duplicates(subset=['model'])

In [14]:
fuelecon[fuelecon["model"]== "Mustang Convertible"]

,make,model,year,vehicle_class,drive,fuel_type,fuel_economy_score,good_fuel_economy?
id,,,,,,,,
32248,Ford,Mustang Convertible,2013,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no

In [15]:
rds_connection_string = "postgres:7924@localhost:5432/ETL_proj"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [16]:
engine.table_names()

['sales_df_yr', 'fueleconomy']

In [17]:
fuelecon.to_sql(name='fueleconomy', con=engine, if_exists='replace', index=True)

In [18]:
with engine.connect() as con:
    con.execute('ALTER TABLE fueleconomy ADD PRIMARY KEY ("model", "year");')