In [16]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [50]:
df = pd.read_csv("fuel_econ.csv")
df.head()

,id,make,model,year,VClass,drive,trans,fuelType,cylinders,displ,pv2,pv4,city,UCity,highway,UHighway,comb,co2,feScore,ghgScore
0,32204,Nissan,GT-R,2013,Subcompact Cars,All-Wheel Drive,Automatic (AM6),Premium Gasoline,6,3.8,79,0,16.4596,20.2988,22.5568,30.1798,18.7389,471,4,4
1,32205,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Automatic (AM-S6),Premium Gasoline,4,2.0,94,0,21.8706,26.9770,31.0367,42.4936,25.2227,349,6,6
2,32206,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Automatic (S6),Premium Gasoline,6,3.6,94,0,17.4935,21.2000,26.5716,35.1000,20.6716,429,5,5
3,32207,Volkswagen,CC 4motion,2013,Compact Cars,All-Wheel Drive,Automatic (S6),Premium Gasoline,6,3.6,94,0,16.9415,20.5000,25.2190,33.5000,19.8774,446,5,5
4,32208,Chevrolet,Malibu eAssist,2013,Midsize Cars,Front-Wheel Drive,Automatic (S6),Regular Gasoline,4,2.4,0,95,24.7726,31.9796,35.5340,51.8816,28.6813,310,8,8

In [80]:
fuelecon = df[['id', 'make', 'model', 'year', 'VClass', 'drive', 'fuelType', 
               'feScore']].copy()

In [81]:
fuelecon.head()

,id,make,model,year,VClass,drive,fuelType,feScore
0,32204,Nissan,GT-R,2013,Subcompact Cars,All-Wheel Drive,Premium Gasoline,4
1,32205,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Premium Gasoline,6
2,32206,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Premium Gasoline,5
3,32207,Volkswagen,CC 4motion,2013,Compact Cars,All-Wheel Drive,Premium Gasoline,5
4,32208,Chevrolet,Malibu eAssist,2013,Midsize Cars,Front-Wheel Drive,Regular Gasoline,8

In [82]:
fuelecon = fuelecon.rename(columns={
    'id': 'ID',
    'make': 'Make',
    'model': 'Model',
    'year': 'Year',
    'VClass': 'Vehicle_Class',
    'drive': 'Drive',
    'fuelType': 'Fuel_Type',
    'feScore': 'Fuel_Economy_Score'
})

In [83]:
fuelecon['Good Fuel Economy?'] = np.where(fuelecon['Fuel_Economy_Score'] > 6, 'yes', 'no')

In [84]:
fuelecon.set_index('ID', inplace = True)

In [85]:
fuelecon.sample(5)

,Make,Model,Year,Vehicle_Class,Drive,Fuel_Type,Fuel_Economy_Score,Good Fuel Economy?
ID,,,,,,,,
35221,Chevrolet,Camaro,2015,Compact Cars,Rear-Wheel Drive,Premium Gasoline,3,no
37830,Kia,Cadenza,2017,Large Cars,Front-Wheel Drive,Regular Gasoline,5,no
32614,Volkswagen,Jetta,2013,Compact Cars,Front-Wheel Drive,Premium Gasoline,7,yes
38144,Mercedes-Benz,AMG S63 4matic Coupe,2017,Compact Cars,4-Wheel Drive,Premium Gasoline,3,no
35611,Volkswagen,Beetle Convertible,2015,Subcompact Cars,Front-Wheel Drive,Diesel,8,yes

In [87]:
fuelecon[fuelecon["Model"]== "Mustang Convertible"]

,Make,Model,Year,Vehicle_Class,Drive,Fuel_Type,Fuel_Economy_Score,Good Fuel Economy?
ID,,,,,,,,
32248,Ford,Mustang Convertible,2013,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
33430,Ford,Mustang Convertible,2014,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
35860,Ford,Mustang Convertible,2015,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,4,no
35861,Ford,Mustang Convertible,2015,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
36879,Ford,Mustang Convertible,2016,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
36883,Ford,Mustang Convertible,2016,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,4,no
37575,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
37579,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no
37584,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
37585,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no
39644,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
39647,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
39651,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no

In [88]:
fuelecon = fuelecon.drop_duplicates(subset=['Model'])

,Make,Model,Year,Vehicle_Class,Drive,Fuel_Type,Fuel_Economy_Score,Good Fuel Economy?
ID,,,,,,,,
32204,Nissan,GT-R,2013,Subcompact Cars,All-Wheel Drive,Premium Gasoline,4,no
32205,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Premium Gasoline,6,no
32207,Volkswagen,CC 4motion,2013,Compact Cars,All-Wheel Drive,Premium Gasoline,5,no
32208,Chevrolet,Malibu eAssist,2013,Midsize Cars,Front-Wheel Drive,Regular Gasoline,8,yes
32209,Lexus,GS 350,2013,Midsize Cars,Rear-Wheel Drive,Premium Gasoline,6,no
...,...,...,...,...,...,...,...,...
39865,BMW,X2 xDrive28i,2018,Midsize Cars,All-Wheel Drive,Premium Gasoline,5,no
39866,Lexus,LS 500h,2018,Midsize Cars,Rear-Wheel Drive,Premium Gasoline,6,no
39867,Lexus,LS 500h AWD,2018,Midsize Cars,All-Wheel Drive,Premium Gasoline,5,no
39900,Lexus,LS 500,2018,Midsize Cars,Rear-Wheel Drive,Premium Gasoline,5,no
39901,Lexus,LS 500 AWD,2018,Midsize Cars,All-Wheel Drive,Premium Gasoline,4,no

In [89]:
fuelecon[fuelecon["Model"]== "Mustang Convertible"]

,Make,Model,Year,Vehicle_Class,Drive,Fuel_Type,Fuel_Economy_Score,Good Fuel Economy?
ID,,,,,,,,
32248,Ford,Mustang Convertible,2013,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
33430,Ford,Mustang Convertible,2014,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
35860,Ford,Mustang Convertible,2015,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,4,no
35861,Ford,Mustang Convertible,2015,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,6,no
36879,Ford,Mustang Convertible,2016,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
36883,Ford,Mustang Convertible,2016,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,4,no
37575,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
37579,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no
37584,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
37585,Ford,Mustang Convertible,2017,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no
39644,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
39647,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,5,no
39651,Ford,Mustang Convertible,2018,Subcompact Cars,Rear-Wheel Drive,Regular Gasoline,3,no

In [58]:
rds_connection_string = "postgres:postgres@localhost:5432/norwaycars"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [59]:
engine.table_names()

['fueleconomy']

In [64]:
fuelecon.to_sql(name='fueleconomy', con=engine, if_exists='replace', index=True)

In [65]:
with engine.connect() as con:
    con.execute('ALTER TABLE fueleconomy ADD PRIMARY KEY ("Model", "Year");')

IntegrityError: (psycopg2.errors.UniqueViolation) could not create unique index "fueleconomy_pkey"
DETAIL:  Key ("Model", "Year")=(Mustang Convertible, 2015) is duplicated.

[SQL: ALTER TABLE fueleconomy ADD PRIMARY KEY ("Model", "Year");]
(Background on this error at: http://sqlalche.me/e/13/gkpj)